Vagrant.configure("2") do |config|

  config.vm.box = "ppggff/centos-7-aarch64-2009-4K"

  # Désactive le partage SMB (évite l'erreur macOS)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "qemu" do |qe|
    qe.memory = "2G"
    qe.ssh_auto_correct = true
  end
  # Start provisioning
  $script = <<-SCRIPT
  echo I am provisioning...
  date > /etc/vagrant_provisioned_at
  SCRIPT
  config.vm.provision "shell",
    inline: $script

  

end
