Vagrant.configure("2") do |config|

  # Désactive le dossier partagé (important sur Mac)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "gitlab_server" do |server|

    server.vm.box = "perk/ubuntu-2204-arm64"

    server.vm.provider "qemu" do |qe|
      qe.arch = "aarch64"
      qe.machine = "virt,accel=hvf,highmem=off"
      qe.cpu = "host"
      qe.memory = "3G"
      qe.smp = "2"
      qe.ssh_auto_correct = true
      qe.net_device = "virtio-net-device"
      qe.qemu_dir = "/opt/homebrew/share/qemu"
    end

  end

end
